// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types.proto

package v2alpha1

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/sensu/sensu-go/apis/meta/v1alpha1"
import _ "github.com/sensu/sensu-proto/protobuf"

import time "time"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

func (r *Rule) Default() {
}

func (r *Role) Default() {
	r.Kind = "Role"
	r.ApiVersion = SchemeGroupVersion.GroupVersionString()
}

func (c *ClusterRole) Default() {
	c.Kind = "ClusterRole"
	c.ApiVersion = SchemeGroupVersion.GroupVersionString()
}

func (r *RoleRef) Default() {
}

func (g *Group) Default() {
	g.Kind = "Group"
	g.ApiVersion = SchemeGroupVersion.GroupVersionString()
}
